workflows:
  expo-android:
    name: Expo Android Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      groups:
        - expo_credentials
      node: 20
      vars:
        EXPO_NO_TELEMETRY: "1"
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: dev
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Run TypeScript check
        script: |
          npx tsc --noEmit
      - name: Build Android app
        script: |
          eas build --platform android --profile production --non-interactive --local
    artifacts:
      - build/*.apk
      - build/*.aab
    publishing:
      email:
        recipients:
          - billmal071@gmail.com 
          - chinedu.design@gmail.com
          - xenon.nemrod@gmail.com
          - ndianguimichelle@gmail.com 
        notify:
          success: true
          failure: true

  expo-ios:
    name: Expo iOS Build
    max_build_duration: 90
    instance_type: mac_mini_m2
    environment:
      groups:
        - expo_credentials
        - ios_credentials
      node: 20
      xcode: latest
      vars:
        EXPO_NO_TELEMETRY: "1"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Run TypeScript check
        script: |
          npx tsc --noEmit
      - name: Build iOS app
        script: |
          eas build --platform ios --profile production --non-interactive --local
    artifacts:
      - build/*.ipa
    publishing:
      email:
        recipients:
          - billmal071@gmail.com 
          - chinedu.design@gmail.com
          - xenon.nemrod@gmail.com
          - ndianguimichelle@gmail.com 
        notify:
          success: true
          failure: true

  expo-preview:
    name: Expo Preview Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      groups:
        - expo_credentials
      node: 20
      vars:
        EXPO_NO_TELEMETRY: "1"
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Run TypeScript check
        script: |
          npx tsc --noEmit
      - name: Build preview APK
        script: |
          eas build --platform android --profile preview --non-interactive --local
    artifacts:
      - build/*.apk
    publishing:
      email:
        recipients:
          - billmal071@gmail.com
          - chinedu.design@gmail.com
          - xenon.nemrod@gmail.com
          - ndianguimichelle@gmail.com 
        notify:
          success: true
          failure: true
