name: OTA Update

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

on:
  push:
    branches: [dev-v1.0.0]
    paths:
      - '**'
      - '!**.md'
      - '!docs/**'
      - '!.eas/workflows/**'

jobs:
  update-dev:
    name: OTA Update (dev)
    type: update
    params:
      branch: development
      message: ${{ github.event.head_commit.message || 'OTA update from dev' }}
