name: OTA Update

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

on:
  push:
    branches: [dev, main]
    paths:
      - '**'
      - '!**.md'
      - '!docs/**'
      - '!.eas/workflows/**'

jobs:
  update-dev:
    name: OTA Update (dev)
    if: ${{ github.ref == 'refs/heads/dev' }}
    type: update
    params:
      branch: development
      message: ${{ github.event.head_commit.message || 'OTA update from dev' }}

  update-production:
    name: OTA Update (production)
    if: ${{ github.ref == 'refs/heads/main' }}
    type: update
    params:
      branch: production
      message: ${{ github.event.head_commit.message || 'OTA update from main' }}
