name: OTA Update (dev)

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

on:
  push:
    branches: [dev]

jobs:
  update:
    name: OTA Update
    type: update
    params:
      branch: ${{ github.ref_name }}
      message: ${{ github.event.head_commit.message || 'OTA update from dev branch' }}
