name: OTA Update

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

on:
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        description: Update channel
        options:
          - development
          - production
        default: development
        required: true
      message:
        type: string
        description: Update message
        required: true

jobs:
  ota-update:
    name: OTA Update (${{ inputs.channel }})
    type: update
    params:
      branch: ${{ inputs.channel }}
      message: ${{ inputs.message }}
